name: Deploy to Azure Function App

on:
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup .NET Core
        uses: actions/setup-dotnet@v2
        with:
          dotnet-version: "8.0.403"

      - name: Publish Function App
        run: |
          dotnet publish WeatherImageGenerator/${{ secrets.START_JOB_FUNCTION }} -c Release -o ./publish
          zip -r ./publish/${{ secrets.START_JOB_FUNCTION }}.zip ./publish

      - name: Deploy to Azure
        uses: azure/webapps-deploy@v2
        with:
          app-name: ${{ secrets.PREFIX }}${{ secrets.START_JOB_FUNCTION }} # Replace with the name of your Azure Function App
          publish-profile: ${{ secrets.AZURE_PUBLISH_PROFILE }}
          package: ./publish/${{ secrets.START_JOB_FUNCTION }}.zip
